language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - yarn

script:
  - node src/tasks/fetchPatrons.js
  - node src/tasks/fetchVideos.js $ytkey
  - yarn unit
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $githubkey
  local-dir: dist
  fqdn: reaction-role.com
  target-branch: master
  on:
    branch: src
